- name: "master-component-setup"
  hosts: masters
  connection: smart
  gather_facts: no

  pre_tasks:
  - name: "profile setup"
    raw: |-
      cat > /tmp/setenv.sh <<EOF
      export V_NAME=`hostname`
      export V_HOST=`ifconfig eth1 | grep 'inet addr' | cut -d: -f2 | awk '{print $1}'`
      EOF
      sudo mv /tmp/setenv.sh /etc/profile.d/

  tasks:
  - name: "master api endpoint setup"
    raw: |-
      . /etc/profile.d/setenv.sh
      sudo system-docker exec etcd etcdctl \
      set /rancher.io/k8s/master "${V_HOST}:8080"

  - name: "kube-apiserver setup"
    raw: |-
      . /etc/profile.d/setenv.sh

      echo \
      "7db2f1c02d721320,kubeadm-node-csr,0615e0ac-7d70-11e7-ad94-fa163eb9dfdd,system:kubelet-bootstrap" \
      > /etc/docker/kube-apiserver/tokens.csv

      sudo system-docker stop kube-apiserver || true
      sudo system-docker rm   kube-apiserver || true
      sudo system-docker run --name=kube-apiserver -d --restart=always \
        --net=host \
        --volumes-from=system-volumes \
        --entrypoint="kube-apiserver" \
        gcr.azk8s.cn/google-containers/kube-apiserver:v1.14.0 \
            --etcd-servers=http://127.0.0.1:2379 \
            --anonymous-auth=false \
            --advertise-address=${V_HOST} \
            --token-auth-file=/etc/docker/kube-apiserver/tokens.csv

  - name: "kube-controller-manager setup"
    raw: |-
      sudo system-docker stop kube-controller-manager || true
      sudo system-docker rm   kube-controller-manager || true
      sudo system-docker run --name=kube-controller-manager -d --restart=always \
        --net=host \
        --volumes-from=system-volumes \
        --entrypoint="kube-controller-manager" \
        gcr.azk8s.cn/google-containers/kube-controller-manager:v1.14.0 \
        --master=127.0.0.1:8080

  - name: "kube-scheduler setup"
    raw: |-
      sudo system-docker stop kube-scheduler || true
      sudo system-docker rm   kube-scheduler || true
      sudo system-docker run --name=kube-scheduler -d --restart=always \
        --net=host \
        --volumes-from=system-volumes \
        --entrypoint="kube-scheduler" \
        gcr.azk8s.cn/google-containers/kube-scheduler:v1.14.0 \
        --master=127.0.0.1:8080

  